#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright (C) 2021 Julian Heuking

send_email() {
	local _subject="${1}"
	# shellcheck disable=2086
	mutt ${CRONCTL_EMAIL_RECEIVER?Missing config option CRONCTL_EMAIL_RECEIVER} \
		-s "${_subject}"
}

run_install_internal() {
	local _method="${1}"
	local _time_spec="${2}"
	local _cron_file="${3}"
	shift 3
	local _cmd="$*"

	local _abs_script_path
	_abs_script_path="$(realpath "${0}")"

	tee "${crontab_d}/${_cron_file}" <<- EOF
		${_time_spec} "${_abs_script_path}" "${_method}" "${_cron_file}" --logfile="${_cron_file}" ${_cmd}
	EOF
	if ! run_update; then
		rm -f "${crontab_d}/${_cron_file}"
		printf 'cronctl update failed' >&2
		exit 1
	fi
}

run_install() {
	run_install_internal exec "$@"
}

run_update() {
	cat "${crontab_d}/"* | crontab -
}

run_exec() {
	local _cronlogs="${HOME}/.local/cronctl/logs"
	mkdir -p "${_cronlogs}"

	export PATH="${PATH}:/usr/local/bin:/usr/bin"
	if printf '%s\n' "${1}" | grep -qE "^--logfile="; then
		logfile="${_cronlogs}/${1#*--logfile=}"
		shift
	else
		logfile="${_cronlogs}/$(basename "${1}")"
	fi
	printf 'Running "%s" at %s...\n' "$*" "$(date +%FT%T)" >> "${logfile}"
	if ! "$@" >> "${logfile}" 2>&1; then
		printf '%s\n' "$@" | send_email "cronjob failed!"
	elif "${CRONCTL_NOTIFY_ALWAYS:-false}"; then
		printf '%s\n' "$@" | send_email "cronjob succeeded!"
	fi
}

run_install_once() {
	local _time="${1}"
	local _cron_file="${2}"
	shift 2

	local _due_time
	_due_time="$(date -d"${_time}" '+%M %H')"
	run_install_internal exec-once "${_due_time} * * *" "${_cron_file}" "$@"
}

set -e
set -u

crontab_d="${HOME}/.config/cronctl/crontab.d"
mkdir -p "${crontab_d}"

config="${HOME}/.config/cronctl/config"
if test -r "${config}"; then
	# shellcheck disable=1090
	. "${config}"
fi

mode="${1?Missing mode}"
shift

case "${mode}" in
	update)
		run_update
		;;
	exec)
		run_exec "$@"
		;;
	exec-once)
		rm -f "${crontab_d}/${1?Missing crontab file}"
		shift
		run_update
		run_exec "$@"
		;;
	install-once)
		run_install_once "$@"
		;;
	install)
		run_install "$@"
		;;
esac
